[theme]
primaryColor = "#368F45"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#0F172A"
font = "sans serif" # Options: "sans serif", "serif", or "monospace"
dataframeHeaderBackgroundColor = "#368f4581"
borderColor = "#0F172A"

[server]
fileWatcherType =. "none"